### ISSUE TITLE
Live transcription

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#429]
**Is your feature request related to a problem? Please describe.**
Transcription is not live rn

**Describe the solution you'd like**
Transcription should be live

**Comment by josancamon19** [comment]
Rn we have a VAD in the backend so that helps determining on the 30 secs chunks, if there's voice in there and requires transcription.

This is saving a ton of transcription credits, right now is close to 1K usd per month.

Restoring live streaming / websockets, could easily go up to 10k per month.

**Comment by josancamon19** [comment]
Maybe defering for now, as it'd be too expensive, or we should start charging users

**Comment by josancamon19** [comment]
MVP ready, but not comfortable releasing that.

So many edge cases.

Some that I can think of right now.

- WebSocket reconnections
   - [x] Keep track of capture seconds so that they make sense.
   - [x] Reconnection is trash, there are too many async events from websockets that is not clear how reconnect should work.
   - [ ] If Websocket reconnects, the track of speakers Id's are lost, so speaker 1 could become now speaker 0, and this is one of the main points of ws -> **PART 2**
   - [x] There are 3 reconnection attempts right now
      - Should we do infinite reconnection attempts?
      - We are sending right now at 3rd attempt failed, a notification telling the user the reconnection failed. If limit reconnect attempts put a button that allows users to reconnect then.
   - [ ] While the websocket is disconnected, or trying to reconnect, those transcription bytes are lost, what can we do so while connection is off, we persist those bytes in a way. Special problem here, when you disable wifi for example, ws doesn't tell automatically, that it disconnected. **PART 2**

- [ ] It will be killed much faster than 30 seconds chunks, what should we do to keep the connection alive? **PART 2**
- [ ] ~It's too expensive, we should charge before releasing this.~
- [x] When you change the language the websocket should be restarted properly as the language changed. Same when speech profile set, as it'd start using soniox instead of deepgram on the backend.
- [x] We need to maintain and better handle people who prefer a non server solution and directly to deepgram, so when they set that on settings and go back it doesnt continue using server, so websocket dies, and 30 seconds chunks start.

**Note:** websocket from app directly to deepgram will not be made, having it to the server is enough of a pain.

**Next Steps:**

**Comment by josancamon19** [comment]
- [ ] Issues connecting soniox websocket on the backend.
    - Make sure it transcribes, and can use diarization + speaker id.
    - Build standard response obj, and check if all works in mobile

**Comment by josancamon19** [comment]
Blocked on speaker profiles, due to soniox websocket
