### ISSUE TITLE
Improve onboarding experience

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#430]
During onboarding

**Comment by josancamon19** [comment]
- [x] Include authentication, so that name fills in "automatically" or pre-fills. Apple Sign In + Google Sign In (Android)
- [ ] ~Then have a screen to double check name, and confirm.~
- [x] The permissions page should also be updated, have a toggle that asks "Allow Friend to learn and communicate", and asks for the proper permissions there.


Auth -> Name -> Permissions -> Connect Device -> Finalize.
