### ISSUE TITLE
Fix non-english languages around the app + webhooks. ($150)

### ISSUE THREAD

**Issue by kodjima33** [BasedHardware/Friend#480]
Check image: https://share.cleanshot.com/15q5t3JX

**Comment by josancamon19** [comment]
Right now, if you change the language to french, spanish, chinese, or anything with non-utf8 characters, it has issues displaying those.

We were doing `utf8.decode((widget.plugin.memoryPrompt ?? '').codeUnits)` but now doesn't seem to work, ideally now, when the transcript is received, it should parse that to decode utf8 automatically, without having to call this in multiple places.

Note: webhooks should also be triggered with utf-8 decoded data, not random symbols

**Comment by josancamon19** [comment]
https://github.com/BasedHardware/Friend/issues/434

**Comment by mdmohsin7** [comment]
@josancamon19 it happens because the [String.codeUnits](https://api.flutter.dev/flutter/dart-core/String/codeUnits.html) method in Dart returns a list of UTF-16 code units, which are 16-bit values representing the characters in the string. When the codeUnits are passed to `utf8.decode`, the decode method will end up truncating the characters incorrectly, especially for characters outside the Basic Multilingual Plane (BMP) that are represented by surrogate pairs in UTF-16. The decode method may work for words where all the codePoints are small enough to not be truncated.

I did fix this issue long back in the [utf-8](https://github.com/BasedHardware/Friend/compare/main...mdmohsin7:Friend:utf-8) branch of my fork. I did it by fixing the problem at root. That is first by decoding the body bytes from response (by default they are utf-8 encoded unless specified in header) and then just directly accessing the string through the code units using `String.fromCharCodes`. Although I believe the first step of decoding the body bytes isn't necessary, we can just use the second step.
