### ISSUE TITLE
Make sure the app never dies while on the background ($150)

### ISSUE THREAD

**Issue by josancamon19** [BasedHardware/Friend#500]
**Is your feature request related to a problem? Please describe.**
Prioritize reliabiliy over battery.

A few minutes after the processing of the app goes on, iOS and android kill the app while on the background.

Fix this so that the app never dies, specially on iOS.

One option is to request the location every 30 seconds to 1 minute, and do something stupid with it so that apple review team approves it.

This should avoid the app to die. Try bee app, it never dies because of the location request, but maybe there are other reasons.

**Comment by acemtp** [comment]
btw, having the position on where the audio was recorded could be an incredible feature.

or grouping memory by places (work, home, etc...)

**Comment by mdmohsin7** [comment]
https://dontkillmyapp.com/

**Comment by mdmohsin7** [comment]
@josancamon19 
I was thinking what if we store multiple locations for a memory? That is let's say if the user travels from one location to another, we will have the record of both the locations which the user can see for that memory. This will give the Apple review team a reason to approve it (`and do something stupid with it so that apple review team approves it.`). You can check the linked PR for more details.

**Comment by josancamon19** [comment]
Closed by @mdmohsin7, just released, will reopen later if performance was not improved on release versions, and based from community feedback
